export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const PRICE_INGREDIENT = 'PRICE_INGREDIENT';

export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS'
export const SYNC_INGREDIENT = 'SYNC_INGREDIENT';
export const SYNC_INGREDIENT_FAILED = 'SYNC_INGREDIENT_FAILED';

export const ORDER = 'ORDER';
export const ORDER_SUCCESFUL = 'ORDER_SUCCESFUL';
export const ORDER_FAILED = 'ORDER_FAILED';
export const ORDER_PROCESSING = 'ORDER_PROCESSING';
export const ORDER_SUBMIT_DONE = 'ORDER_SUBMIT_DONE';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER = 'FETCH_ORDER';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';

export const AUTH = 'AUTH';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const SESSION_TIMEOUT_INITIATE = 'SESSION_TIMEOUT_INITIATE';
export const SESSION_TIMEOUT = 'SESSION_TIMEOUT';
export const FETCH_SESSION = 'FETCH_SESSION'
export const CLEAR_SESSION = 'CLEAR_SESSION';

export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT'
